name: Build & Push Open WebUI to GHCR (amd64)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.svelte'
      - 'backend/**'
      - 'frontend/**'
      - 'Dockerfile'
      - '.github/workflows/docker-ghcr.yml'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/champig4c/open-webui
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
